### ISSUE TITLE
Change `ignore_list` to `allow_list`

### ISSUE THREAD

**Issue by gvdhoven** [zxdavb/evohome_cc#1]
Just a suggestion, instead of opting out (e.g. blacklist way), it might be a idea to change this to a white-list way; e.g. add option `allow_list` which would mean only those controllers would be connected to.

**Comment by zxdavb** [comment]
This functionality already exists - it is not enabled/documented intentionally, but will be 'released' at some time in the future.  ALl you have to do is get rid of the `#` (see below), and add the relevant section to **configuration.yaml**.

https://github.com/zxdavb/evohome_cc/blob/b9e94803a342757158c3ac387b1f4211b190bd35/__init__.py#L53

It is left out because the code is still in a test/dev stage & it makes it easier for me.

**Comment by zxdavb** [comment]
This feature has been added to v0.5.0+
