### ISSUE TITLE
Add additional attributes to actuator binary sensor

### ISSUE THREAD

**Issue by phdelodder** [zxdavb/evohome_cc#17]
Can the attributes listed below be add to the actuator binary sensor? 
```
OTB:040239         | CTL:223036         | RP | actuator_state   | 00001... || {'actuator_enabled': False, 'modulation_level': 0.0, '_unknown_0': '10', 'flame_active': False, 'flame_state': '00', '_unknown_1': '00FF020A64'}
```

With:
```
'10:040239': {'actuator_cycle': None, 'actuator_state': None, 'boiler_setpoint': None, 'modulation_level': 0.0, 'opentherm_status': {'boiler_temp': None, 'ch_pressure': None, 'dhw_flow_rate': None, 'dhw_temp': None, 'rel_modulation_level': None, 'return_cv_temp': None}}}
```

**Comment by zxdavb** [comment]
This is not that easy, because of the way **evohome** devices are mapped to home assistant.

This device - an OTB - is actually two distinct 'things' - a OpenTherm bridge, and a _heater relay_ - and so you would expect it to be implemented twice in HA (however, I'm ignoring OT presently)... actually, it's worse than that!

One issue is that a _heater relay_ can be either a OpenTherm bridge (**R8810**), or a simple relay (a **BDR91**) - they have several properties in common, and others not (one modulates, the other uses TPI).

The other issue is that HA wants 'physical' devices split out into multiple HA entities - think about a TRV, which is *four* such HA entities:
 - 2x binary_sensors: `battery_low`, `window_open`
 - 2x sensors: `heat_demand`, `temperature`

Now, it also has an attribute, `setpoint` - this can reasonably be a state_attribute of the TRV, but of which of the three HA entities should be be a property of - all four? This leads to repetition and is somewhat unsatisfactory & I wont countenance it...

I have attached it to the `temperature` entity, but you could reasonably argue it should with be `heat_demand`.

I do not want to implement something, then have to undo it - so we move slowly on this.

**Comment by zxdavb** [comment]
@phdelodder Can you close this, or provide more feedback? If it is still an issue, I can have a look at it.
